### ISSUE TITLE
Feature Request: Support for Categories

### ISSUE THREAD

**Issue by badewanne1234** [partofthething/next-holiday-sensor#10]
Hi

The python-holiday library has additional categories which are listed for many countries, for example the "BANK" holiday category. [(https://github.com/vacanza/python-holidays?tab=readme-ov-file#available-countries)](https://python-holidays.readthedocs.io/en/latest/#available-countries)

However, it does not seem to be supported by this integration at this stage. From what I can tell, only "PUBLIC" is supported. It would be of great help if the additional categories can also be supported.

Thank you

**Comment by badewanne1234** [comment]
I just found this is already possible with the `kwargs` option.

Here is an example with two categories:
```
  - platform: next_holiday
    min_future_holidays: 3
    sources: 
     - country: "Belgium"
       observed: false
       kwargs:
         categories: 'public'
     - country: "Belgium"
       observed: false
       kwargs:
         categories: 'bank'
```
