### ISSUE TITLE
Feature Request: Supported Language attributes

### ISSUE THREAD

**Issue by sinowine** [partofthething/next-holiday-sensor#7]
Hi Nick, 
would it be possible to include the "Supported Language" attribute that exists in the python-holidays library so that the holidays can be displayed in the local language?

**Comment by sinowine** [comment]
Tried the "language: de" under attribute kwargs but nothing has changed for me. Restarted ha and cleared the browser cache many times.😩

**Comment by partofthething** [comment]
Sorry it's not working. Which country are you using in combination with the de language? Is the country/language supported per [this table](https://python-holidays.readthedocs.io/en/latest/#available-countries)?

I've updated the documentation that fixed #5 in this commit 5452f0c8c57192cb124ba8535e98599ec34484e0, but we still need to figure out what the issue is for you.

**Comment by sinowine** [comment]
Yes, it is. 

- platform: next_holiday
  min_future_holidays: 3
  custom_holidays:
    "10-31": "Halloween"
  sources:
    - country: "DE"
      state: "BE"
      kwargs:
        language: "de"

**Comment by partofthething** [comment]
Thanks. It may just be the formatting of the paste you put in, but do you have an indent after the kwargs? It should be like this:

```
platform: next_holiday
min_future_holidays: 3
custom_holidays:
"10-31": "Halloween"
sources:
    country: "DE"
    state: "BE"
    kwargs:
        language: "de"

```
