### ISSUE TITLE
Doc Request - Automation Conditions Tuturial/Examples

### ISSUE THREAD

**Issue by alexwitherspoon** [partofthething/next-holiday-sensor#9]
Howdy! 

This is a super rad plugin, and I think it might be helpful to suggest how it might be used for automations in HA. For example if a user wanted to create a simple automation that turned on 'Christmas lights' if Christmas was the next holiday and it was 14 days until Christmas <- How would we best do that? 

I can create some template values paired with a simple numeric state. The template value gets slightly more complicated for some users, and with the attribute nesting HA/Jinja doesn't seem happy at me. Any tips to help with condition writing? And maybe if so there are a few good additions to docs to help folks get started?

```
{{ 'christmas' in states.sensor.next_holiday.next_holiday_future.holiday }}
```

The above errors out with the following:
> In 'template' condition: UndefinedError: 'homeassistant.helpers.template.TemplateState object' has no attribute 'next_holiday_future'

AND 

```
condition: numeric_state
entity_id: sensor.next_holiday
attribute: days_until_next_holiday
below: 14
```

Happy to PR some docs up, but first I'd need to understand how it works, and how I am messing up. Thanks!

**Comment by partofthething** [comment]
Hi. Good points. thanks for saying so. 

> For example if a user wanted to create a simple automation that turned on 'Christmas lights' if Christmas was the next holiday and it was 14 days until Christmas <- How would we best do that?

That would be a template condition with something like: 

```yaml
condition:
  alias: "Almost Christmas!"
  condition: template
  value_template: >
     {{ states('sensor.next_holiday') == 'Christmas' and 
        state_attr('sensor.next_holiday','days_until_next_holiday') < 14  }}
```

Or I believe you could do the AND condition thing you're mentioning without templates like:

```yaml
condition:
  alias: "Christmas is near!"
  condition: and
  conditions:
    - condition: state
      entity_id: sensor.next_holiday
      state: "Christmas"
    - condition: numeric_state
      entity_id: sensor.next_holiday
      attribute: days_until_next_holiday
      below: 14
```

I'll add this and a few other examples to the docs if this helps.
